services:
  mongodb:
    image: 'mongo:latest'
    container_name: "mongod"
    networks:
        - learning
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  
  pythonapp:
    build: ./
    image: mgdb:container
    container_name: "dbContainer"
    networks:
        - learning
    depends_on:
      mongodb:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  learning:
