[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86-64"

[default_config.opts]
compiler = "nasm"
compile_flags_txt = [ "-f", "elf64" , "-g", "-F", "dwarf" ]
diagnostics = true
default_diagnostics = false
no_output_files = true
